# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Cid', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('Cuid', models.IntegerField(db_column='Cuid', max_length=11)),
                ('Ctime', models.DateTimeField(default=datetime.datetime(2017, 11, 11, 9, 57, 43, 463469))),
                ('Clight', models.IntegerField(default=0, max_length=4)),
                ('Cfloor', models.IntegerField(default=0, max_length=4)),
                ('Ccontent', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=20)),
                ('Eaddress', models.CharField(max_length=100)),
                ('Eopentime', models.DateTimeField()),
                ('Emax_num', models.IntegerField(default=0, max_length=4)),
                ('Eonce_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='playground',
            fields=[
                ('Pid', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=20, unique=True)),
                ('Pinfomation', models.CharField(max_length=400)),
                ('Popentime', models.DateTimeField(db_column='Popentime')),
                ('Ptel', models.IntegerField(max_length=8)),
                ('Padderss', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('proid', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('proname', models.CharField(max_length=30)),
                ('prodesc', models.CharField(max_length=400)),
                ('pmark', models.FloatField()),
                ('proplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.playground')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date pushlished')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('Tid', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('Ttype', models.CharField(default='空', max_length=20)),
                ('Tprice', models.FloatField(default=0.0)),
                ('Tdatetime', models.DateTimeField()),
                ('TplaygroundId_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.playground')),
                ('Tproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project')),
            ],
        ),
        migrations.CreateModel(
            name='userBaseInfo',
            fields=[
                ('Uid', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('Uname', models.CharField(max_length=20)),
                ('Utel', models.IntegerField(max_length=8)),
                ('Usign', models.CharField(max_length=200)),
                ('Usex', models.CharField(max_length=2)),
                ('Ubirthdate', models.DateField(default=datetime.date(2017, 11, 11))),
            ],
        ),
        migrations.CreateModel(
            name='userDynamicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIid', models.IntegerField(max_length=11)),
                ('Uaddress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.IntegerField(max_length=4)),
                ('Uticketstatus', models.IntegerField(default=0, max_length=4)),
                ('Uticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Cproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
