# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('proid', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('proname', models.CharField(max_length=30)),
                ('prodesc', models.CharField(max_length=400)),
                ('pmark', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='TplaygroundId',
            new_name='TplaygroundId_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='Ctime',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 22, 43, 36, 842068)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Tproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project'),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='Uticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ticket'),
        ),
    ]
